import logging

from ..base.base_node import BaseNode

logger = logging.getLogger(__name__)


class ColoredNode(BaseNode):

    def _build_logger(self):
        return logging.LoggerAdapter(
            logger,
            {
                "node_id": self.id,
                "node_type": self.__class__.__name__,
            },
        )

    def do_submodule_things(self):

        self.logger.warning(
            "This log is a warning generated by a submodule, and is colored green"
        )
        self.logger.info(
            "This log is a info generated by a submodule, and is colored yellow"
        )
        self.logger.error(
            "This log is an error generated by a submodule, and is colored red"
        )
